// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1chhGkPHLAmLPiqMstT5UcnPNI5hqOY',
    appId: '1:1017128864839:web:7bd2a9981ebbd4733d3562',
    messagingSenderId: '1017128864839',
    projectId: 'birthflowdev',
    authDomain: 'birthflowdev.firebaseapp.com',
    storageBucket: 'birthflowdev.firebasestorage.app',
    measurementId: 'G-6B822ERSLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0yP7rM9FXabvvchDql7TTZVd4Ksd3Wos',
    appId: '1:1017128864839:android:f8e69af071774bcc3d3562',
    messagingSenderId: '1017128864839',
    projectId: 'birthflowdev',
    storageBucket: 'birthflowdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGO-4nkO7xFAUlfjjUfmfAlMR1teRY7fs',
    appId: '1:1017128864839:ios:2ebe87e015e5f94c3d3562',
    messagingSenderId: '1017128864839',
    projectId: 'birthflowdev',
    storageBucket: 'birthflowdev.firebasestorage.app',
    iosBundleId: 'com.example.birthflowMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGO-4nkO7xFAUlfjjUfmfAlMR1teRY7fs',
    appId: '1:1017128864839:ios:2ebe87e015e5f94c3d3562',
    messagingSenderId: '1017128864839',
    projectId: 'birthflowdev',
    storageBucket: 'birthflowdev.firebasestorage.app',
    iosBundleId: 'com.example.birthflowMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY1chhGkPHLAmLPiqMstT5UcnPNI5hqOY',
    appId: '1:1017128864839:web:5a862993a280f1d53d3562',
    messagingSenderId: '1017128864839',
    projectId: 'birthflowdev',
    authDomain: 'birthflowdev.firebaseapp.com',
    storageBucket: 'birthflowdev.firebasestorage.app',
    measurementId: 'G-LS8RP61WSV',
  );
}
